source 'https://git.coding.net/hging/Specs.git'
platform :ios, "8.0"
use_frameworks!

pod 'SwiftHEXColors', '~> 1.0.4'
pod 'MJRefresh', '~> 3.1.12'
pod 'SnapKit', '~> 0.22.0'
pod 'MBProgressHUD', '~> 0.9.0'
pod 'Alamofire', '~> 3.5.1'
pod 'AlamofireNetworkActivityIndicator', '~> 1.1.0'
pod 'SDCycleScrollView', '~> 1.65'
pod 'Kingfisher', '~>2.6.1'
pod 'Kanna', '~> 1.1.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'IQKeyboardManagerSwift', '4.0.5'
pod 'Siren', '0.9.5'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'KMPlaceholderTextView', '~> 1.2.2'
pod 'SVWebViewController', '~> 1.0'
